select distinct ?capital ?latitudeDegrees ?latitudeMinutes str(?latitudeNS) ?longitudeDegrees ?longitudeMinutes str(?longitudeEW) where 
{
        #TODO: might need to bind strings to actual fields
	?country a dbo:Country.
        ?country dbo:flag ?flag.
	{
		{?country dbo:capital ?capital}
		UNION
		{?country dbp:capital ?capital}
	}

	
	FILTER(contains(str(?capital), %CAPITAL_URL%)))

        # GPS Coordinates
        ?country dbp:latd ?latitudeDegrees.
        ?country dbp:latm ?latitudeMinutes.
        ?country dbp:latns ?latitudeNS. # North - South

        ?country dbp:longd ?longitudeDegrees.
        ?country dbp:longm ?longitudeMinutes.
        ?country dbp:longew ?longitudeEW. # East - West
}
order by ?capital
