select distinct ?capital ?labelS ?labelC1 ?labelC2 where 
{
	{
		{?country dbo:capital ?capital}
		UNION
		{?country dbp:capital ?capital}
	}
	?country a dbo:Country.

	?country dbo:language ?lang.
	?lang dbo:iso6391Code ?code.

	?country rdfs:label ?labelS. 
	?capital rdfs:label ?labelC1. 
	?capital rdfs:label ?labelC2. 
        
	# Example URL
	FILTER(contains(str(?capital), %CAPITAL_URL%))
	FILTER(lang(?labelS) = 'en')
	FILTER(lang(?labelC1) = 'en')
	FILTER(lang(?labelC2) = ?code)
}
LIMIT 1