select distinct ?capital ?image where 
{
	
      ?capital foaf:depiction ?image.
        


	FILTER(str(?capital) = %CAPITAL_URL%)
	#FILTER(contains(str(?capital), "http://dbpedia.org/resource/Algiers"))
}
order by ?capital
limit 1