select distinct ?capital ?page where 
{
	
      ?capital foaf:homepage ?page.
        


	FILTER(str(?capital) = "http://dbpedia.org/resource/Berlin")
	#FILTER(contains(str(?capital), "http://dbpedia.org/resource/Algiers"))
}
order by ?capital
limit 1