select distinct ?capitalName xsd:integer(?popTotal) xsd:integer(?popYear) where 
{
	#TODO: might need to bind return value to an actual field
	?country a dbo:Country.
	?country dbo:flag ?flag.
	{
		{?country dbo:capital ?capital}
		UNION
		{?country dbp:capital ?capital}
	}
	?capital foaf:name ?capitalName.

	FILTER(contains(str(?capital), %CAPITAL_URL%))

	# Total Population
	?capital dbo:populationTotal ?popTotal.
	OPTIONAL {?capital dbp:popYear ?popYear.}
}