select distinct ?abstractString where 
{
	?country a dbo:Country.
	?country dbo:flag ?flag.
	{
		{?country dbo:capital ?capital}
		UNION
		{?country dbp:capital ?capital}
	}

	# Example URL
	# FILTER(contains(str(?capital), "http://dbpedia.org/resource/Berlin"))
	FILTER(str(?capital) = %CAPITAL_URL%)
	FILTER(lang(?abstract) = 'en')

	?capital dbo:abstract ?abstract.

        BIND(str(?abstract) AS ?abstractString)
}
