SELECT DISTINCT ?capital ?labelState ?labelCity ?labelCityLocal WHERE
{
	{
		{?country dbo:capital ?capital}
		UNION
		{?country dbp:capital ?capital}
	}
	?country a dbo:Country.

	?country rdfs:label ?labelState. 
	?capital rdfs:label ?labelCity. 

	?country dbo:language ?lang.
	# This needs to be optional as not every language has a code
	OPTIONAL
	{
		?lang dbo:iso6391Code ?code.
		?capital rdfs:label ?labelCityLocal.
		FILTER(lang(?labelCityLocal) = ?code)
	}
        
	# Example URL
	# FILTER(contains(str(?capital), "http://dbpedia.org/resource/Paris"))
	FILTER(contains(str(?capital), %CAPITAL_URL%))
	FILTER(lang(?labelState) = 'en')
	FILTER(lang(?labelCity) = 'en')
} LIMIT 1
