select distinct ?capital ?labelState ?labelCity ?labelCityLocal where 
{
	{
		{?country dbo:capital ?capital}
		UNION
		{?country dbp:capital ?capital}
	}
	?country a dbo:Country.

	?country dbo:language ?lang.
	?lang dbo:iso6391Code ?code.

	?country rdfs:label ?labelState. 
	?capital rdfs:label ?labelCity. 
	?capital rdfs:label ?labelCityLocal. 
        
	FILTER(contains(str(?capital), %CAPITAL_URL%))
	FILTER(lang(?labelState) = 'en')
	FILTER(lang(?labelCity) = 'en')
	FILTER(lang(?labelCityLocal) = ?code)
}
LIMIT 1
