SELECT DISTINCT ?capital ?image WHERE
{	
	?capital foaf:depiction ?image.
        
	FILTER(str(?capital) = %CAPITAL_URL%)
	#FILTER(contains(str(?capital), "http://dbpedia.org/resource/Algiers"))
}
LIMIT 1
