SELECT DISTINCT ?capital ?leaderNameString ?nameString WHERE
{
	{
		{
			{?capital dbo:leaderName ?leaderName}
			UNION
			{?capital dbp:leaderName ?leaderName}
		}
		UNION
		{?capital dbo:mayor ?leaderName}
	}

	OPTIONAL{?leaderName foaf:name ?name}
        BIND(str(?leaderName) AS ?leaderNameString)
        BIND(str(?name) AS ?nameString)

	# Example URL
	# FILTER(str(?capital) = "http://dbpedia.org/resource/Algiers"))
	FILTER(str(?capital) = %CAPITAL_URL%)
}
LIMIT 1
