SELECT DISTINCT ?capital ?leaderString ?nameString where
{
		{?capital dbo:leaderName ?leader}
		UNION
		{?capital dbp:leaderName ?leader}
		UNION
		{?capital dbp:leader ?leader}
		UNION
		{?capital dbo:leader ?leader}
		UNION
		{?capital dbo:mayor ?leader}
		FILTER(str(?capital) = %CAPITAL_URL%)
		OPTIONAL{?leader rdf:type ?typeLeader}
		FILTER(?typeLeader = foaf:Person || ?typeLeader = dbo:Person || !CONTAINS(str(?leader),"http://"))
		OPTIONAL{?leader foaf:name ?name}
		BIND(str(?leader) as ?leaderString)
		BIND(IF(CONTAINS(str(?leader),"http://"), str(?name), str(?leader)) as ?nameString)
}
LIMIT 1