select distinct ?mottoString where 
{
	?country a dbo:Country.
	?country dbo:flag ?flag.
	{
		{?country dbo:capital ?capital}
		UNION
		{?country dbp:capital ?capital}
	}

	FILTER(str(?capital) = %CAPITAL_URL%)

	# Motto
	{
		{?capital dbp:cityMotto ?motto.}
		UNION
		{?capital dbo:motto ?motto.}
	}
	BIND(str(?motto) AS ?mottoString)
	FILTER(!contains(str(?motto), "()"))
}
