select distinct ?popTotalInt ?popYearInt where 
{
	?country a dbo:Country.
	?country dbo:flag ?flag.
	{
		{?country dbo:capital ?capital}
		UNION
		{?country dbp:capital ?capital}
	}

	FILTER(str(?capital) = %CAPITAL_URL%)

	# Total Population
	?capital dbo:populationTotal ?popTotal.
	BIND(xsd:integer(?popTotal) AS ?popTotalInt)
	OPTIONAL {?capital dbp:popYear ?popYear.}
	BIND(xsd:integer(?popYear) AS ?popYearInt)
}
