# A region can be a district, division, country, etc.
SELECT DISTINCT ?regionName ?typeRegion WHERE
{
	?country a dbo:Country.
	?country dbo:flag ?flag.
	{
		{?country dbo:capital ?capital}
		UNION
		{?country dbp:capital ?capital}
	}
	
	# Example URL
	# FILTER(contains(str(?capital), "http://dbpedia.org/resource/Berlin"))
	FILTER(str(?capital) = %CAPITAL_URL%)

	# Region
	OPTIONAL{
		{ ?capital dbo:region ?region }
		UNION
		{ ?capital dbo:isPartOf ?region }
		?region <http://purl.org/linguistics/gold/hypernym> ?typeRegion.
		FILTER (?typeRegion = dbr:Area || ?typeRegion = dbr:Communities
			|| ?typeRegion = dbr:Counties || ?typeRegion = dbr:Department || ?typeRegion = dbr:Division || ?typeRegion = dbr:Divisions
			|| ?typeRegion = dbr:District || ?typeRegion = dbr:Districts || ?typeRegion = dbr:Governorate || ?typeRegion = dbr:Governorates
			|| ?typeRegion = dbr:Oblast || ?typeRegion = dbr:Province || ?typeRegion = dbr:Provinces || ?typeRegion = dbr:Regions || ?typeRegion = dbr:Units
			|| ?typeRegion = dbr:Zones )
	}
        ?region rdfs:label ?regionLabel
        FILTER(lang(?regionLabel) = 'en')

        BIND(str(?regionLabel) AS ?regionName)
}
