PREFIX dboPop: <http://dbpedia.org/ontology/PopulatedPlace/>
SELECT DISTINCT ?areaDouble WHERE
{
	?country a dbo:Country.
	?country dbo:flag ?flag.
	{
		{?country dbo:capital ?capital}
		UNION
		{?country dbp:capital ?capital}
	}

	# Example URL
	FILTER(str(?capital) = %CAPITAL_URL%)

	# Total Area in square meters
	?capital dboPop:areaTotal ?area.
	BIND(xsd:double(?area) AS ?areaDouble)
}
